#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")/.."
VERSION="${1:?Supply the release version}"
: "${CODE_SIGN_IDENTITY:?Set your Developer ID identity}"
: "${CODE_SIGN_KEYCHAIN:?Set your signing Keychain}"
: "${NOTARY_PROFILE:?Set your notarization Keychain profile}"
NOTARYTOOL="${NOTARYTOOL:-$(xcrun --find notarytool)}"
STAPLER="${STAPLER:-$(xcrun --find stapler)}"
APP="$PWD/build/Desktop LEDs.app"
OUT="$PWD/release"
NAME="FS-Desktop-LEDs-$VERSION-arm64"
mkdir -p "$OUT"
codesign --verify --deep --strict "$APP"
ditto -c -k --sequesterRsrc --keepParent "$APP" "$OUT/notarization.zip"
"$NOTARYTOOL" submit "$OUT/notarization.zip" --keychain-profile "$NOTARY_PROFILE" --wait --output-format json > "$OUT/app-notary.json"
python3 -c 'import json,sys; assert json.load(open(sys.argv[1]))["status"] == "Accepted"' "$OUT/app-notary.json"
"$STAPLER" staple "$APP"
"$STAPLER" validate "$APP"
spctl --assess --type execute --verbose=2 "$APP"
ditto -c -k --sequesterRsrc --keepParent "$APP" "$OUT/$NAME.zip"
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT
ditto "$APP" "$STAGE/Desktop LEDs.app"
ln -s /Applications "$STAGE/Applications"
hdiutil create -volname 'FS Desktop LEDs' -srcfolder "$STAGE" -ov -format UDZO "$OUT/$NAME.dmg"
codesign --force --timestamp --sign "$CODE_SIGN_IDENTITY" --keychain "$CODE_SIGN_KEYCHAIN" "$OUT/$NAME.dmg"
"$NOTARYTOOL" submit "$OUT/$NAME.dmg" --keychain-profile "$NOTARY_PROFILE" --wait --output-format json > "$OUT/dmg-notary.json"
python3 -c 'import json,sys; assert json.load(open(sys.argv[1]))["status"] == "Accepted"' "$OUT/dmg-notary.json"
"$STAPLER" staple "$OUT/$NAME.dmg"
"$STAPLER" validate "$OUT/$NAME.dmg"
spctl --assess --type open --context context:primary-signature --verbose=2 "$OUT/$NAME.dmg"
(cd "$OUT" && shasum -a 256 "$NAME.dmg" "$NAME.zip" > SHA256SUMS)
printf 'Ready to publish: %s\n' "$OUT/$NAME.dmg"
